### ISSUE TITLE
Chartwerk doesn't show up in Grafana Plugins

### ISSUE THREAD

**Issue by sonejostudios** [chartwerk/grafana-chartwerk-app#52]
Hi all,

I'm using Grafana 6.7.3, I installed Chartwerk correctly, I restarted Grafana many time, but Chartwerk doesn't show up in Grafana's Plugin page.

I assume it is installed correctly because I installed many other plugins the same way, and they work correctly.

Is there a compatibility issue between Chartwerk and my version of Grafana?

---

Small bugfix: the installation command in the README.MD is wrong: 
`wget https://github.com/chartwerk/grafana-chartwerk-panel/archive/0.1.2.zip`

"-panel" should be replaced by "app"

---
Thank a million for any hint!
All the best

Vince

**Comment by jonyrock** [comment]
Hey @sonejostudios thank you for the report. We will check this issue in this week.

**Comment by rozetko** [comment]
Hi @sonejostudios 
What is the way you've used to install the plugin? Please, specify the steps.
Do you see the plugin name in Grafana logs on restart (like on the screenshot below)? Or is there some error instead maybe?
![image](https://user-images.githubusercontent.com/1989898/94011863-b1f64680-fdb0-11ea-817f-806434659ae5.png)

P.S. the plugin should work fine with Grafana 6.7.3

**Comment by sonejostudios** [comment]
Hey!

thank you very much for the report. I re-installed it according to 

https://github.com/chartwerk/grafana-chartwerk-app

and now it is working.. I don't know what went wrong last time. 
Anyway, thank you very much for the support,

all the best

vince

**Comment by rozetko** [comment]
thanks for the feedback, we'll change the link
