### ISSUE TITLE
Plugin crash when selecting Chartwerk

### ISSUE THREAD

**Issue by mamartins** [chartwerk/grafana-chartwerk-app#56]
When I select Chartwerk as the visualisation for a query it crashes with the following:
```
An unexpected error happened
TypeError: undefined is not an object (evaluating 'this.events.emit')

    in t
    in x
    in to
    in div
    in div
    in t
    in t
    in div
    in Mo
    in div
    in div
    in vo
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l 
```

**Comment by jonyrock** [comment]
Hey. We will fix it this week

**Comment by jonyrock** [comment]
Hey @mamartins this is issue we fixed https://github.com/chartwerk/grafana-chartwerk-app/issues/51 , but released. Please try chartwerk from master. We will make release this week anyway.

**Comment by rozetko** [comment]
Hey @mamartins, this issue is fixed in the new release: https://github.com/chartwerk/grafana-chartwerk-app/releases/tag/0.2.0

**Comment by mamartins** [comment]
Thank you! I can confirm that it is working.
